name: build and push noclouds

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: build&push
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4
      
      - name: log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: build image
        run: docker build . -t ${{ secrets.DOCKERHUB_USER }}/noclouds:latest

      - name: push image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/noclouds:latest
